// Auto-generated by `npm run gen:openapi` (manually stubbed for type-check until generation run).
// Minimal subset of paths used in the UI.
export interface paths {
	'/api/health': {
		get: {
			responses: {
				200: { content: { 'application/json': { status: string; timestamp: string } } }
			}
		}
	};
	'/api/investigations': {
		get: {
			parameters?: any;
			responses: {
				200: { content: { 'application/json': any[] } }
			}
		};
		post: {
			requestBody: any;
			responses: {
				200: { content: { 'application/json': { investigation_id: string } } } | {
					201: { content: { 'application/json': { investigation_id: string } } }
				}
			}
		}
	};
}
export interface components {}
