[tool.ruff]
line-length = 88
exclude = ["osint_env", "theHarvester", "output", "venv", "Sublist3r", "**/site-packages/**", "*.md"]
target-version = "py312"

[tool.mypy]
exclude = [
    # Exclude root-level Python files that conflict with package modules
    ".*/[^/]+\\.py$",
    # Exclude common non-source directories
    "osint_env/",
    "theHarvester/",
    "output/",
    "venv/",
    "Sublist3r/",
    ".*/site-packages/.*",
    ".*/__pycache__/.*",
    ".*/\\.mypy_cache/.*",
]
follow_imports = "silent"
namespace_packages = true
