name: Container Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

env:
  IMAGE_NAME: watchman89/passive-osint-suite

jobs:
  trivy-scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: |
          docker pull $IMAGE_NAME:latest || true

      - name: Trivy Image Scan (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-image.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          vuln-type: os,library

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
