name: Container Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

env:
  IMAGE_NAME: watchman89/passive-osint-suite

jobs:
  trivy-scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: |
          docker pull $IMAGE_NAME:latest || true

      - name: Trivy Image Scan (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-image.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          vuln-type: os,library

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif

      - name: Dockle - container best practices lint
        uses: goodwithtech/dockle-action@v1
        with:
          image: ${{ env.IMAGE_NAME }}:latest
          exit-code: 1
          timeout: 5m
          # Skip checks that are incompatible with our design (non-root enforced, secrets)
          # You can tune these as policy evolves
          accept-keywords: |
            CIS-DI-0010
            CIS-DI-0001
            DKL-DI-0006

  policy-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conftest
        uses: instrumenta/conftest-action@v0.4.0
      - name: Run policy checks on Compose
        run: |
          set -euo pipefail
          conftest test -p policies docker-compose.yml
          if [ -f docker-compose.override.hardened.yml ]; then
            conftest test -p policies docker-compose.override.hardened.yml
          fi
