name: Container Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run dockle
        uses: goodwithtech/dockle-action@v0.4.15
        with:
          image: ${{ github.event.repository.name }}
          dockerfile: Dockerfile
