name: Build and Push Docker Image (SBOM + Provenance)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch: {}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  packages: write

env:
  IMAGE_NAME: watchman89/passive-osint-suite

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push (with SBOM + provenance)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true

      - name: Cosign sign (keyless)
        env:
          COSIGN_EXPERIMENTAL: 1
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          # Sign the canonical latest tag
          cosign sign --yes $IMAGE_NAME:latest

      - name: Cosign verify
        env:
          COSIGN_EXPERIMENTAL: 1
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          cosign verify $IMAGE_NAME:latest
