name: Lint Dockerfile (Hadolint)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
            dockerfile: Dockerfile
            config: .hadolint.yaml
