name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the Docker image (with cache)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: my-image-name:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
