name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check if Docker build needed
      id: check_docker
      run: |
        # For PRs, compare against the base branch; for pushes, compare against previous commit
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          if git diff --name-only $BASE_SHA HEAD | grep -qE '^(Dockerfile|requirements.*\.txt)'; then
            echo "docker_changed=true" >> $GITHUB_OUTPUT
          else
            echo "docker_changed=false" >> $GITHUB_OUTPUT
          fi
        elif git diff --name-only HEAD~1 HEAD | grep -qE '^(Dockerfile|requirements.*\.txt)'; then
          echo "docker_changed=true" >> $GITHUB_OUTPUT
        else
          echo "docker_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      if: steps.check_docker.outputs.docker_changed == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image (with cache)
      if: steps.check_docker.outputs.docker_changed == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: my-image-name:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
