name: Python Lint (Ruff)

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff==0.8.0

      - name: Run Ruff (check)
        run: ruff check .

      - name: Run Ruff Format (check)
        run: ruff format --check .
