name: Python Lint (Ruff)

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ruff (check)
        uses: astral-sh/ruff-action@v1
        with:
          version: 0.7.2
          args: check .

      - name: Run Ruff Format (check)
        uses: astral-sh/ruff-action@v1
        with:
          version: 0.7.2
          args: format --check .
