name: Trivy Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '**.py'
      - '.github/workflows/trivy-scan.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '**.py'
      - '.github/workflows/trivy-scan.yml'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (with cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: passive-osint-suite:scan
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
        timeout-minutes: 15

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        continue-on-error: true
        with:
          image-ref: 'passive-osint-suite:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build, just report
          ignore-unfixed: true
          timeout: 15m

      - name: Check if SARIF file exists
        if: always()
        run: |
          if [ -f trivy-results.sarif ]; then
            echo "SARIF file exists, will upload"
            echo "SARIF_EXISTS=true" >> $GITHUB_ENV
          else
            echo "SARIF file does not exist, skipping upload"
            echo "SARIF_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && env.SARIF_EXISTS == 'true'
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner (table format)
        uses: aquasecurity/trivy-action@0.28.0
        if: always()
        continue-on-error: true
        with:
          image-ref: 'passive-osint-suite:scan'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
          ignore-unfixed: true
          timeout: 15m
