name: Trivy Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/trivy-scan.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - 'requirements*.txt'
      - '.github/workflows/trivy-scan.yml'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if Docker build needed
        id: check_docker
        run: |
          # For PRs, compare against the base branch; for pushes, compare against previous commit
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            if git diff --name-only $BASE_SHA HEAD | grep -qE '^(Dockerfile|requirements.*\.txt)'; then
              echo "docker_changed=true" >> $GITHUB_OUTPUT
            else
              echo "docker_changed=false" >> $GITHUB_OUTPUT
            fi
          elif git diff --name-only HEAD~1 HEAD | grep -qE '^(Dockerfile|requirements.*\.txt)'; then
            echo "docker_changed=true" >> $GITHUB_OUTPUT
          else
            echo "docker_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check_docker.outputs.docker_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (with cache)
        if: steps.check_docker.outputs.docker_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: passive-osint-suite:scan
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
        timeout-minutes: 30

      - name: Run Trivy vulnerability scanner
        if: steps.check_docker.outputs.docker_changed == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        continue-on-error: true
        with:
          image-ref: 'passive-osint-suite:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build, just report
          ignore-unfixed: true
          timeout: 15m

      - name: Check if SARIF file exists
        if: always() && steps.check_docker.outputs.docker_changed == 'true'
        run: |
          if [ -f trivy-results.sarif ]; then
            echo "SARIF file exists, will upload"
            echo "SARIF_EXISTS=true" >> $GITHUB_ENV
          else
            echo "SARIF file does not exist, skipping upload"
            echo "SARIF_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check_docker.outputs.docker_changed == 'true' && env.SARIF_EXISTS == 'true'
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner (table format)
        if: always() && steps.check_docker.outputs.docker_changed == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        continue-on-error: true
        with:
          image-ref: 'passive-osint-suite:scan'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
          ignore-unfixed: true
          timeout: 15m
